INSERT INTO kanji_words (id, kanji, reading, meaning, example_sentence, example_reading, example_meaning, grade) VALUES
  ('k001', '山',   'やま',       'Mountain',                    '富士山は日本で一番高い山です。',             'ふじさんはにほんでいちばんたかいやまです。',             'Mt. Fuji is the tallest mountain in Japan.',          1),
  ('k002', '川',   'かわ',       'River',                       'この川はとてもきれいです。',                 'このかわはとてもきれいです。',                           'This river is very clean.',                           1),
  ('k003', '花',   'はな',       'Flower',                      '春にはたくさんの花が咲きます。',             'はるにはたくさんのはながさきます。',                     'Many flowers bloom in spring.',                       1),
  ('k004', '空',   'そら',       'Sky',                         '今日の空はとても青いです。',                 'きょうのそらはとてもあおいです。',                       'The sky is very blue today.',                         1),
  ('k005', '雨',   'あめ',       'Rain',                        '明日は雨が降るでしょう。',                   'あしたはあめがふるでしょう。',                           'It will probably rain tomorrow.',                     1),
  ('k006', '時間', 'じかん',     'Time',                        '時間がありません。',                         'じかんがありません。',                                   'There is no time.',                                   2),
  ('k007', '友達', 'ともだち',   'Friend',                      '友達と公園で遊びました。',                   'ともだちとこうえんであそびました。',                     'I played with my friend at the park.',                2),
  ('k008', '天気', 'てんき',     'Weather',                     '今日はいい天気ですね。',                     'きょうはいいてんきですね。',                             'The weather is nice today, isn''t it?',               2),
  ('k009', '勉強', 'べんきょう', 'Study',                       '毎日日本語を勉強しています。',               'まいにちにほんごをべんきょうしています。',               'I study Japanese every day.',                         3),
  ('k010', '漢字', 'かんじ',     'Chinese characters / Kanji',  '漢字を覚えるのは大変です。',                 'かんじをおぼえるのはたいへんです。',                     'Memorizing kanji is tough.',                          3),
  ('k011', '世界', 'せかい',     'World',                       '世界中を旅行したいです。',                   'せかいじゅうをりょこうしたいです。',                     'I want to travel around the world.',                  3),
  ('k012', '経験', 'けいけん',   'Experience',                  'いい経験になりました。',                     'いいけいけんになりました。',                             'It was a good experience.',                           4),
  ('k013', '挑戦', 'ちょうせん', 'Challenge',                   '新しいことに挑戦するのが好きです。',         'あたらしいことにちょうせんするのがすきです。',           'I like to challenge myself with new things.',         4),
  ('k014', '環境', 'かんきょう', 'Environment',                 '環境を守ることは大切です。',                 'かんきょうをまもることはたいせつです。',                 'Protecting the environment is important.',            5),
  ('k015', '想像', 'そうぞう',   'Imagination',                 '想像以上に難しかったです。',                 'そうぞういじょうにむずかしかったです。',                 'It was harder than I imagined.',                      5);
