INSERT INTO kanji_words (id, kanji, reading, meaning, example_sentence, example_reading, example_meaning, grade) VALUES
  ('k001', '山', 'やま', 'Mountain', '富士山は日本で一番高い山です。', 'ふじさんはにほんでいちばんたかいやまです。', 'Mt. Fuji is the tallest mountain in Japan.', 1),
  ('k002', '川', 'かわ', 'River', 'この川はとてもきれいです。', 'このかわはとてもきれいです。', 'This river is very clean.', 1),
  ('k003', '花', 'はな', 'Flower', '春にはたくさんの花が咲きます。', 'はるにはたくさんのはながさきます。', 'Many flowers bloom in spring.', 1),
  ('k004', '空', 'そら', 'Sky', '今日の空はとても青いです。', 'きょうのそらはとてもあおいです。', 'The sky is very blue today.', 1),
  ('k005', '雨', 'あめ', 'Rain', '明日は雨が降るでしょう。', 'あしたはあめがふるでしょう。', 'It will probably rain tomorrow.', 1),
  ('k006', '月', 'つき', 'Moon', '今夜の月はとてもきれいです。', 'こんやのつきはとてもきれいです。', 'The moon is very beautiful tonight.', 1),
  ('k007', '火', 'ひ', 'Fire', '火を使うときは気をつけてください。', 'ひをつかうときはきをつけてください。', 'Please be careful when using fire.', 1),
  ('k008', '水', 'みず', 'Water', '水を飲みたいです。', 'みずをのみたいです。', 'I want to drink water.', 1),
  ('k009', '森', 'もり', 'Forest', '森の中を歩くのが好きです。', 'もりのなかをあるくのがすきです。', 'I like walking in the forest.', 1),
  ('k010', '犬', 'いぬ', 'Dog', 'あの犬はとてもかわいいです。', 'あのいぬはとてもかわいいです。', 'That dog is very cute.', 1),
  ('k011', '時間', 'じかん', 'Time', '時間がありません。', 'じかんがありません。', 'There is no time.', 2),
  ('k012', '友達', 'ともだち', 'Friend', '友達と公園で遊びました。', 'ともだちとこうえんであそびました。', 'I played with my friend at the park.', 2),
  ('k013', '天気', 'てんき', 'Weather', '今日はいい天気ですね。', 'きょうはいいてんきですね。', 'The weather is nice today, isn''t it?', 2),
  ('k014', '元気', 'げんき', 'Energy / Health', 'お元気ですか。', 'おげんきですか。', 'How are you?', 2),
  ('k015', '教室', 'きょうしつ', 'Classroom', '教室に生徒がたくさんいます。', 'きょうしつにせいとがたくさんいます。', 'There are many students in the classroom.', 2),
  ('k016', '毎朝', 'まいあさ', 'Every morning', '毎朝六時に起きます。', 'まいあさろくじにおきます。', 'I wake up at six every morning.', 2),
  ('k017', '風', 'かぜ', 'Wind', '今日は風が強いです。', 'きょうはかぜがつよいです。', 'The wind is strong today.', 2),
  ('k018', '歌', 'うた', 'Song', 'この歌がとても好きです。', 'このうたがとてもすきです。', 'I like this song very much.', 2),
  ('k019', '電話', 'でんわ', 'Telephone', '母に電話をかけました。', 'ははにでんわをかけました。', 'I called my mother.', 2),
  ('k020', '新聞', 'しんぶん', 'Newspaper', '父は毎朝新聞を読みます。', 'ちちはまいあさしんぶんをよみます。', 'My father reads the newspaper every morning.', 2),
  ('k021', '勉強', 'べんきょう', 'Study', '毎日日本語を勉強しています。', 'まいにちにほんごをべんきょうしています。', 'I study Japanese every day.', 3),
  ('k022', '漢字', 'かんじ', 'Chinese characters / Kanji', '漢字を覚えるのは大変です。', 'かんじをおぼえるのはたいへんです。', 'Memorizing kanji is tough.', 3),
  ('k023', '世界', 'せかい', 'World', '世界中を旅行したいです。', 'せかいじゅうをりょこうしたいです。', 'I want to travel around the world.', 3),
  ('k024', '植物', 'しょくぶつ', 'Plant', 'この植物は水が少なくても育ちます。', 'このしょくぶつはみずがすくなくてもそだちます。', 'This plant grows even with little water.', 3),
  ('k025', '宿題', 'しゅくだい', 'Homework', '宿題を忘れてしまいました。', 'しゅくだいをわすれてしまいました。', 'I forgot my homework.', 3),
  ('k026', '温度', 'おんど', 'Temperature', '今日の温度は三十度です。', 'きょうのおんどはさんじゅうどです。', 'Today''s temperature is 30 degrees.', 3),
  ('k027', '問題', 'もんだい', 'Problem / Question', 'この問題はとても難しいです。', 'このもんだいはとてもむずかしいです。', 'This problem is very difficult.', 3),
  ('k028', '図書館', 'としょかん', 'Library', '図書館で本を借りました。', 'としょかんでほんをかりました。', 'I borrowed a book from the library.', 3),
  ('k029', '発表', 'はっぴょう', 'Presentation / Announcement', '明日クラスで発表があります。', 'あしたくらすではっぴょうがあります。', 'There is a presentation in class tomorrow.', 3),
  ('k030', '安全', 'あんぜん', 'Safety', '安全に気をつけてください。', 'あんぜんにきをつけてください。', 'Please be careful about safety.', 3),
  ('k031', '経験', 'けいけん', 'Experience', 'いい経験になりました。', 'いいけいけんになりました。', 'It was a good experience.', 4),
  ('k032', '挑戦', 'ちょうせん', 'Challenge', '新しいことに挑戦するのが好きです。', 'あたらしいことにちょうせんするのがすきです。', 'I like to challenge myself with new things.', 4),
  ('k033', '選挙', 'せんきょ', 'Election', '来月選挙が行われます。', 'らいげつせんきょがおこなわれます。', 'An election will be held next month.', 4),
  ('k034', '必要', 'ひつよう', 'Necessary', 'パスポートが必要です。', 'ぱすぽーとがひつようです。', 'A passport is necessary.', 4),
  ('k035', '結果', 'けっか', 'Result', '試験の結果を待っています。', 'しけんのけっかをまっています。', 'I am waiting for the exam results.', 4),
  ('k036', '伝説', 'でんせつ', 'Legend', 'この村には古い伝説があります。', 'このむらにはふるいでんせつがあります。', 'This village has an old legend.', 4),
  ('k037', '季節', 'きせつ', 'Season', '日本には四つの季節があります。', 'にほんにはよっつのきせつがあります。', 'Japan has four seasons.', 4),
  ('k038', '約束', 'やくそく', 'Promise', '友達と約束をしました。', 'ともだちとやくそくをしました。', 'I made a promise with my friend.', 4),
  ('k039', '健康', 'けんこう', 'Health', '健康のために毎日運動しています。', 'けんこうのためにまいにちうんどうしています。', 'I exercise every day for my health.', 4),
  ('k040', '失敗', 'しっぱい', 'Failure', '失敗を恐れないでください。', 'しっぱいをおそれないでください。', 'Don''t be afraid of failure.', 4),
  ('k041', '環境', 'かんきょう', 'Environment', '環境を守ることは大切です。', 'かんきょうをまもることはたいせつです。', 'Protecting the environment is important.', 5),
  ('k042', '想像', 'そうぞう', 'Imagination', '想像以上に難しかったです。', 'そうぞういじょうにむずかしかったです。', 'It was harder than I imagined.', 5),
  ('k043', '準備', 'じゅんび', 'Preparation', '旅行の準備をしています。', 'りょこうのじゅんびをしています。', 'I am preparing for a trip.', 5),
  ('k044', '価値', 'かち', 'Value / Worth', 'この本は読む価値があります。', 'このほんはよむかちがあります。', 'This book is worth reading.', 5),
  ('k045', '演説', 'えんぜつ', 'Speech', '大統領が演説を行いました。', 'だいとうりょうがえんぜつをおこないました。', 'The president gave a speech.', 5),
  ('k046', '貿易', 'ぼうえき', 'Trade', '日本は多くの国と貿易をしています。', 'にほんはおおくのくにとぼうえきをしています。', 'Japan trades with many countries.', 5),
  ('k047', '犯罪', 'はんざい', 'Crime', '犯罪を減らすために何ができますか。', 'はんざいをへらすためになにができますか。', 'What can we do to reduce crime?', 5),
  ('k048', '複雑', 'ふくざつ', 'Complex / Complicated', 'この問題は複雑です。', 'このもんだいはふくざつです。', 'This problem is complicated.', 5),
  ('k049', '限界', 'げんかい', 'Limit / Boundary', '自分の限界に挑戦したい。', 'じぶんのげんかいにちょうせんしたい。', 'I want to challenge my limits.', 5),
  ('k050', '能力', 'のうりょく', 'Ability / Capacity', '彼女は高い能力を持っています。', 'かのじょはたかいのうりょくをもっています。', 'She has high ability.', 5),
  ('k051', '私立', 'しりつ', 'Private (institution)', '姉は私立の大学に通っています。', 'あねはしりつのだいがくにかよっています。', 'My sister attends a private university.', 6),
  ('k052', '疑問', 'ぎもん', 'Question / Doubt', '疑問があれば聞いてください。', 'ぎもんがあればきいてください。', 'Please ask if you have any questions.', 6),
  ('k053', '尊敬', 'そんけい', 'Respect', '先生を尊敬しています。', 'せんせいをそんけいしています。', 'I respect my teacher.', 6),
  ('k054', '秘密', 'ひみつ', 'Secret', 'これは二人だけの秘密です。', 'これはふたりだけのひみつです。', 'This is a secret just between us two.', 6),
  ('k055', '創造', 'そうぞう', 'Creation', '創造力を大切にしましょう。', 'そうぞうりょくをたいせつにしましょう。', 'Let''s value creativity.', 6),
  ('k056', '忠告', 'ちゅうこく', 'Advice / Warning', '友人の忠告を聞くべきでした。', 'ゆうじんのちゅうこくをきくべきでした。', 'I should have listened to my friend''s advice.', 6),
  ('k057', '存在', 'そんざい', 'Existence', '彼の存在はとても大きいです。', 'かれのそんざいはとてもおおきいです。', 'His presence is very significant.', 6),
  ('k058', '権利', 'けんり', 'Rights', 'すべての人に平等な権利があります。', 'すべてのひとにびょうどうなけんりがあります。', 'All people have equal rights.', 6),
  ('k059', '批判', 'ひはん', 'Criticism', '批判を受け入れることも大切です。', 'ひはんをうけいれることもたいせつです。', 'It''s also important to accept criticism.', 6),
  ('k060', '閣僚', 'かくりょう', 'Cabinet minister', '閣僚が会議に出席しました。', 'かくりょうがかいぎにしゅっせきしました。', 'The cabinet ministers attended the meeting.', 6),
  ('k061', '偶然', 'ぐうぜん', 'Coincidence', '駅で偶然友達に会いました。', 'えきでぐうぜんともだちにあいました。', 'I ran into a friend by coincidence at the station.', 7),
  ('k062', '矛盾', 'むじゅん', 'Contradiction', '彼の話には矛盾があります。', 'かれのはなしにはむじゅんがあります。', 'There is a contradiction in his story.', 7),
  ('k063', '謙虚', 'けんきょ', 'Humble / Modest', '謙虚な姿勢が大切です。', 'けんきょなしせいがたいせつです。', 'A humble attitude is important.', 7),
  ('k064', '憂鬱', 'ゆううつ', 'Depression / Melancholy', '雨の日は少し憂鬱です。', 'あめのひはすこしゆううつです。', 'Rainy days make me a little gloomy.', 7),
  ('k065', '把握', 'はあく', 'Grasp / Understanding', '状況を把握する必要があります。', 'じょうきょうをはあくするひつようがあります。', 'We need to grasp the situation.', 7),
  ('k066', '迅速', 'じんそく', 'Swift / Prompt', '迅速な対応をお願いします。', 'じんそくなたいおうをおねがいします。', 'Please respond promptly.', 7),
  ('k067', '克服', 'こくふく', 'Overcoming', '困難を克服しました。', 'こんなんをこくふくしました。', 'I overcame the difficulty.', 7),
  ('k068', '曖昧', 'あいまい', 'Ambiguous / Vague', '曖昧な返事はやめてください。', 'あいまいなへんじはやめてください。', 'Please stop giving vague answers.', 7),
  ('k069', '濫用', 'らんよう', 'Abuse / Misuse', '権力の濫用は許されません。', 'けんりょくのらんようはゆるされません。', 'Abuse of power is not permitted.', 7),
  ('k070', '賠償', 'ばいしょう', 'Compensation / Reparation', '被害者に賠償金が支払われました。', 'ひがいしゃにばいしょうきんがしはらわれました。', 'Compensation was paid to the victims.', 7);
